import os
from sqlalchemy import create_engine, Column, Integer, String, Float, DateTime, JSON, Text
from sqlalchemy.orm import declarative_base, sessionmaker
from datetime import datetime

# Define the project's base directory (one directory above this file)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
DB_PATH = os.path.join(BASE_DIR, 'data', 'ai_investment_research.db')

# Create the data directory if it doesn't exist
os.makedirs(os.path.dirname(DB_PATH), exist_ok=True)

engine = create_engine(f'sqlite:///{DB_PATH}', echo=False)
Base = declarative_base()

class Opportunity(Base):
    __tablename__ = 'opportunities'
    
    id = Column(Integer, primary_key=True)
    symbol = Column(String(10), nullable=False)
    company_name = Column(String(100), nullable=True) # Nom descriptiu de l'empresa
    date_detected = Column(DateTime, default=datetime.utcnow)
    strategy_name = Column(String(50), nullable=False)
    current_price = Column(Float, nullable=False)
    target_price = Column(Float, nullable=True) # Fase 2
    stop_loss = Column(Float, nullable=True)    # Fase 2
    strategy_config = Column(JSON, nullable=True) # Save the configuration used
    market_context = Column(Text, nullable=True)  # Generated by AI
    explanation = Column(Text, nullable=True)     # Generated by AI
    metrics = Column(JSON, nullable=True)         # Numerical signal data
    market = Column(String(50), nullable=True)    # Index where found (sp500, ibex35, etc.)
    currency = Column(String(10), nullable=True)  # Currency (EUR, USD, etc.)

class StrategyConfig(Base):
    __tablename__ = 'strategy_configs'
    
    id = Column(Integer, primary_key=True)
    strategy_name = Column(String(50), unique=True, nullable=False)
    parameters = Column(JSON, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

# Create or update the schema
Base.metadata.create_all(engine)

SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

def get_db():
    """Generator to obtain the database session"""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
